export const ERROR_MESSAGES = {
    "admin-restricted-operation": "Esta operación está restringida solo a administradores.",
    "argument-error": "",
    "app-not-authorized": "Esta aplicación, identificada por el dominio en el que está alojada, no está autorizada para usar Firebase Authentication con la clave de API proporcionada. Revise la configuración de su clave en la consola de API de Google.",
    "app-not-installed": "La aplicación móvil solicitada correspondiente al identificador (nombre del paquete de Android o identificador del paquete de iOS) proporcionado no está instalada en este dispositivo.",
    "captcha-check-failed": "El token de respuesta de reCAPTCHA proporcionado es inválido, ha expirado, ya se ha utilizado o el dominio asociado con él no coincide con la lista de dominios en la lista blanca.",
    "code-expired": "El código SMS ha caducado. Vuelva a enviar el código de verificación para intentarlo de nuevo.",
    "cordova-not-ready": "El framework de Cordova no está listo.",
    "cors-unsupported": "Este navegador no es compatible.",
    "credential-already-in-use": "Esta credencial ya está asociada con una cuenta de usuario diferente.",
    "custom-token-mismatch": "El token personalizado corresponde a una audiencia diferente.",
    "requires-recent-login": "Esta operación es sensible y requiere autenticación reciente. Inicie sesión de nuevo antes de volver a intentar esta solicitud.",
    "dynamic-link-not-activated": "Active los vínculos dinámicos en la Consola de Firebase y acepte los términos y condiciones.",
    "email-change-needs-verification": "Los usuarios de múltiples factores siempre deben tener un correo electrónico verificado.",
    "email-already-in-use": "La dirección de correo electrónico ya está en uso por otra cuenta.",
    "expired-action-code": "El código de acción ha caducado. ",
    "cancelled-popup-request": "Esta operación se ha cancelado debido a que se ha abierto otra ventana emergente conflictiva.",
    "internal-error": "Se ha producido un error interno.",
    "invalid-app-credential": "La solicitud de verificación de teléfono contiene un verificador de aplicaciones no válido. La respuesta del token de reCAPTCHA es inválida o ha caducado.",
    "invalid-app-id": "El identificador de la aplicación móvil no está registrado para el proyecto actual.",
    "invalid-user-token": "La credencial de este usuario no es válida para este proyecto. Esto puede suceder si el token del usuario ha sido manipulado o si el usuario no está para el proyecto asociado con esta clave API.",
    "invalid-auth-event": "Se ha producido un error interno.",
    "invalid-verification-code": "El código de verificación SMS utilizado para crear la credencial de autenticación telefónica es inválido. Vuelva a enviar el SMS de verificación del código y asegúrese de utilizar el código de verificación proporcionado por el usuario.",
    "invalid-continue-uri": "La URL de continuación proporcionada en la solicitud es inválida.",
    "invalid-cordova-configuration": "Los siguientes plugins de Cordova deben estar instalados para habilitar el inicio de sesión OAuth: cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser y cordova-plugin-customurlscheme.",
    "invalid-custom-token": "El formato del token personalizado es incorrecto. Por favor, consulte la documentación.",
    "invalid-dynamic-link-domain": "El dominio de enlaces dinámicos proporcionado no está configurado ni autorizado para el proyecto actual.",
    "invalid-email": "La dirección de correo electrónico tiene un formato incorrecto.",
    "invalid-api-key": "La clave API no es válida, por favor, verifique que la ha copiado correctamente.",
    "invalid-cert-hash": "El valor hash del certificado SHA-1 proporcionado no es válido.",
    "invalid-credential": "La credencial de autenticación suministrada tiene un formato incorrecto o ha caducado.",
    "invalid-message-payload": "La plantilla de correo electrónico correspondiente a esta acción contiene caracteres no válidos en su mensaje. Por favor, soluciónelo accediendo a la sección de plantillas de correo electrónico de Firebase Console.",
    "invalid-multi-factor-session": "La solicitud no contiene una prueba válida de inicio de sesión con éxito del primer factor.",
    "invalid-oauth-provider": "EmailAuthProvider no es compatible con esta operación. Esta operación solo admite proveedores de OAuth.",
    "invalid-oauth-client-id": "El ID de cliente de OAuth proporcionado no es válido o no coincide con la clave API especificada.",
    "unauthorized-domain": "Este dominio no está autorizado para operaciones de OAuth para su proyecto Firebase. Edite la lista de dominios autorizados desde la consola de Firebase.",
    "invalid-action-code": "El código de acción no es válido. Esto puede ocurrir si el código tiene un formato incorrecto, ha caducado o ya ha sido utilizado.",
    "wrong-password": "La contraseña es inválida o el usuario no tiene una contraseña.",
    "invalid-persistence-type": "El tipo de persistencia especificado no es válido. Solo puede ser local, de sesión o ninguno.",
    "invalid-provider-id": "El ID de proveedor especificado no es válido.",
    "invalid-recipient-email": "El correo electrónico correspondiente a esta acción no se pudo enviar porque la dirección de correo electrónico del destinatario proporcionada no es válida.",
    "invalid-sender": "La plantilla de correo electrónico correspondiente a esta acción contiene una dirección de correo electrónico o nombre de remitente no válido. Por favor, soluciónelo accediendo a la sección de plantillas de correo electrónico de Firebase Console.",
    "invalid-verification-id": "El ID de verificación utilizado para crear la credencial de autenticación telefónica es inválido.",
    "invalid-tenant-id": "El ID de inquilino de la instancia de Autenticación no es válido.",
    "multi-factor-info-not-found": "El usuario no tiene un segundo factor que coincida con el identificador proporcionado.",
    "multi-factor-auth-required": "Se requiere una prueba de propiedad de un segundo factor para completar el inicio de sesión.",
    "auth-domain-config-required": "Asegúrese de incluir authDomain al llamar a firebase.initializeApp(), siguiendo las instrucciones en la consola de Firebase."
  };
